export { default as InputMethodConfig } from './InputMethodConfig.vue'
export { default as GlobalConfig } from './GlobalConfig.vue'
export { default as ThemeConfig } from './ThemeConfig.vue'
export { default as AdvancedConfig } from './AdvancedConfig.vue'
export { default as GearButton } from './GearButton.vue'
